### ISSUE TITLE
DataStore2 API to manage datastores for users not in-game

### ISSUE THREAD

**Issue by Nyapaw** [Kampfkarren/Roblox#86] opened 2019-12-24 23:31 UTC
Self-explanatory.
If combined datastores are not needed, then MasterKey functions as a key.

Examples:
`GetId(MasterKey, Key, UserId)`
`SetId(MasterKey, Key, UserId, Value)`
...

**Comment by Kampfkarren** [comment] 2019-12-24 23:53
Duplicate of #44

**Closed by Kampfkarren** 2019-12-24 23:53 UTC
